"""empty message

Revision ID: 83be34b0ebd9
Revises: 
Create Date: 2023-11-21 10:11:24.890249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83be34b0ebd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
