"""empty message

Revision ID: d16f039b53fd
Revises: 
Create Date: 2023-12-13 00:57:50.458581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16f039b53fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Upload_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'username')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('Upload_image')
    # ### end Alembic commands ###
